[package]
name = "cr023"
version = "1.0.0"
edition = "2021"

[dependencies]
yew = "0.19.3"
web-sys = "0.3.68"
wasm-bindgen = "0.2.91"
wasm-bindgen-futures = "0.4.42"
serde = { version = "1.0.37", features = ["derive"] }
serde_json = "1.0.81"
reqwasm = "0.5.0"
regex = "1.10.4"