[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.19.3" }
stylist = { version = "0.10.0", features = ["yew"] }
web-sys = "0.3.68"
wasm-bindgen = "0.2.91"